### ISSUE TITLE
Switch over to redhat-ci for docker-storage-setup

### ISSUE THREAD

**Issue by jlebon** [projectatomic/paci#1]
Once https://github.com/projectatomic/docker-storage-setup/pull/182 is merged, we need to move over homu to make use of the "required" status so that we can decommission the old tester.

**Comment by jlebon** [comment]
If it's less overhead for you, we could also pretend that https://github.com/cgwalters/projectatomic-ci-infra-secrets/blob/master/homu/cfg.toml is already live and I can just submit patches to that myself (and let you take care of copying it back in place to your server).

**Comment by jlebon** [comment]
PR merged! \o/

**Comment by cgwalters** [comment]
Should be done.
