### ISSUE TITLE
Question about 3.6.1 OCP

### ISSUE THREAD

**Issue by peterbaouoft** [projectatomic/paci#11]
Hi, I was following the instructions from https://github.com/projectatomic/paci/tree/master/jenkins.  However, I was unable to run `oc cluster up --version=3.6.1` because my version of origin-clients is 3.6.0. I also happened to find a [issue](https://github.com/openshift/origin/issues/17821) related to it. 

I tried `dnf upgrade origin-clients`, but no upgrade is available yet.  Any suggestions for how to upgrade a package without upgrading the whole system? Or, what other problems I might need to worry about if I used the 3.6.0 OCP cluster? I was running on fedora 27 cloud, with origin-clients 3.6.0. Thanks

**Comment by jlebon** [comment]
I honestly just download `oc` from the latest stable release: https://github.com/openshift/origin/releases. And then extract it into `/usr/local/bin`.

**Comment by peterbaouoft** [comment]
:O, cool, no need to rebuild the binaries? nice :), the steps seem a lot easier than I expected then. lemme try that out. Thanks.

**Comment by peterbaouoft** [comment]
Yup, that indeed solves the problem. interesting that oc binary already contain all of its dependencies too. I used wget to get the image, and that took a while #facepalm. I will close this issue then. Thanks.
