### ISSUE TITLE
RFC: Rename this repo to something less wordy

### ISSUE THREAD

**Issue by jlebon** [projectatomic/paci#6]
`projectatomic/projectatomic-ci-infra` is redundant. :)
How do we feel about `projectatomic/ci`, or `projectatomic/paci`?

**Comment by cgwalters** [comment]
I like `paci` a bit more.

Any objections to doing that rename?

**Comment by jlebon** [comment]
`paci` is my preference as well!

**Comment by cgwalters** [comment]
Done!
